framework:
  messenger:
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: "doctrine://default?queue_name=failed"
      # sync: 'sync://'

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default: []
      

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
      App\Command\Course\CreateCourseCommand: async
      App\Command\Course\CreateFullCourseCommand: async
      App\Command\Course\DeleteCourseCommand: async
      App\Command\Course\UpdateCourseCommand: async
      App\Command\Instructor\RegisterInstructorCommand: async
      App\Command\Lesson\AddResourceToLessonCommand: async
      App\Command\Lesson\ConvertLessonToRegisteredCommand: async
      App\Command\Lesson\CreateLessonCommand: async
      App\Command\Lesson\DeleteLessonCommand: async
      App\Command\Lesson\EditLessonCommand: async
      App\Command\User\EditUserCommand: async
      App\Command\User\UpdateUserPasswordCommand: async

      # Route your messages to the transports
      # 'App\Message\YourMessage': async
