nelmio_api_doc:
    documentation:
        info:
            title: MS-LEARNING
            description: ONLINE LEARNING PLATFORM 
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)
