api_login_check:
  path: /api/login_check

App\Controller\authentification\RegisterController:
  resource: routes/register.yaml
  prefix: /api
  name_prefix: "user_"

App\Controller\authentification\LoginController:
  resource: routes/login.yaml
  prefix: /api
  name_prefix: "user_"

App\Controller\authentification\PasswordResetController:
  resource: routes/forgot.yaml
  prefix: /
  name_prefix: "forgot_"

App\Controller\authentification\AuthController:
  resource: routes/oauth.yaml
  prefix: /
  name_prefix: "auth_"

App\Controller\Category\CategoryController:
  resource: routes/categories.yaml
  prefix: /
  name_prefix: "api_category_"

App\Controller\Course\CoursesController:
  resource: routes/courses.yaml
  prefix: /
  name_prefix: "courses_"

App\Controller\BecomeInstructor\BecomeInstructor:
  resource: routes/becomeinstructor.yaml
  prefix: /
  name_prefix: "becomeinstructor_"

App\Controller\User\UserController:
  resource: routes/user.yaml
  prefix: /
  name_prefix: "users_"

App\Controller\User\InstructorDemands:
  resource: routes/instructorDemands.yaml
  prefix: /
  name_prefix: "instructordemands_"

App\Controller\Lesson\LessonController:
  resource: routes/lesson.yaml
  prefix: /
  name_prefix: "lessons_"

App\Controller\msconnect\post\PostController:
  resource: routes/post.yaml
  prefix: /
  name_prefix: "post_"

App\Controller\msconnect\comment\CommentController:
  resource: routes/comment.yaml
  prefix: /
  name_prefix: "comment_"

App\Controller\msconnect\forum\ForumPostController:
  resource: routes/forum.yaml
  prefix: /
  name_prefix: "forum_"

App\Controller\msconnect\message\MessagesController:
  resource: routes/message.yaml
  prefix: /
  name_prefix: "message_"

App\Controller\chatbot\ChatbotController:
  resource: routes/chatbot.yaml
  prefix: /
  name_prefix: "chatbot_"

App\Controller\Testimonials\TestimonialController:
  resource: routes/testimonial.yaml
  prefix: /
  name_prefix: "testimonial_"  

App\Controller\Faq\FaqController:
  resource: routes/faq.yaml
  prefix: /
  name_prefix: "faq_"  

App\Controller\Plan\PlanController:
  resource: routes/Plan.yaml
  prefix: /
  name_prefix: "plan_"  

