api_login_check:
  path: /api/login_check
  
App\Controller\authentification\RegisterController:
    resource: routes/register.yaml
    prefix: /api
    name_prefix: 'user_'

App\Controller\authentification\LoginController:
    resource: routes/login.yaml
    prefix: /api
    name_prefix: 'user_'

App\Controller\authentification\PasswordResetController:
    resource: routes/forgot.yaml
    prefix: /
    name_prefix: 'forgot_'      

App\Controller\authentification\AuthController:
  resource: routes/oauth.yaml
  prefix: /
  name_prefix: 'auth_'

App\Controller\Category\CategoryController:
  resource: routes/categories.yaml
  prefix: /
  name_prefix: 'api_category_'

App\Controller\\Course\CoursesController:
  resource: routes/courses.yaml
  prefix: /
  name_prefix: 'api_courses_'  
