index:
  path: /categories
  controller: App\Controller\Category\CategoryController::index
  methods: GET

show:
  path: /categories/{id}
  controller: App\Controller\Category\CategoryController::show
  methods: GET

create:
  path: /categories
  controller: App\Controller\Category\CategoryController::create
  methods: POST

update:
  path: /categories/{id}
  controller: App\Controller\Category\CategoryController::update
  methods: PUT

delete:
  path: /categories/{id}
  controller: App\Controller\Category\CategoryController::delete
  methods: DELETE
