index:
  path: /courses
  controller: App\Controller\Course\CoursesController::index
  methods: GET

show:
  path: /course/{id}
  controller: App\Controller\Course\CoursesController::show
  methods: GET

create:
  path: /courses
  controller: App\Controller\Course\CoursesController::create
  methods: POST

create_Instructor:
  path: instructor/course/create
  controller: App\Controller\Course\CoursesController::createCourse
  methods: POST

update:
  path: /course/{id}
  controller: App\Controller\Course\CoursesController::update
  methods: PUT

delete:
  path: /course/{id}
  controller: App\Controller\Course\CoursesController::delete
  methods: DELETE
