index:
  path: /courses
  controller: App\Controller\Course\CoursesController::index
  methods: GET

latestCourses:
  path: /courses/latest
  controller: App\Controller\Course\CoursesController::getLatestCourses
  methods: GET

FreeCourses:
  path: /courses/free
  controller: App\Controller\Course\CoursesController::getFreeCourses
  methods: GET

RecommendedCourses:
  path: /courses/recommended/{id}
  controller: App\Controller\Course\CoursesController::getRecommendedCourses
  methods: GET

show:
  path: /course/{id}
  controller: App\Controller\Course\CoursesController::show
  methods: GET

enrolled_course:
  path: /enrolledCourse/{id}
  controller: App\Controller\Course\CoursesController::enrolledCourse
  methods: GET

course_content:
  path: /coursecontent/{id}
  controller: App\Controller\Course\CoursesController::getCourseWithModulesAndLessons
  methods: GET

courses_by_category:
  path: /courses/by-category/{id}
  controller: App\Controller\Course\CoursesController::getCoursesByCategory
  methods: GET

create:
  path: /courses
  controller: App\Controller\Course\CoursesController::create
  methods: POST

create_Instructor:
  path: instructor/course/create
  controller: App\Controller\Course\CoursesController::createCourse
  methods: POST

update:
  path: /course/{id}
  controller: App\Controller\Course\CoursesController::update
  methods: PUT

delete:
  path: /course/{id}
  controller: App\Controller\Course\CoursesController::delete
  methods: DELETE

courses:
  path: /coursesmodules/user/{id}
  controller: App\Controller\Course\CoursesController::getUserCoursesModules
  methods: GET

courses_modules_lessons:
  path: /coursesmoduleslessons/user/{id}
  controller: App\Controller\Course\CoursesController::getCoursesModulesLessonsWithoutResources
  methods: GET
