index:
  path: users
  controller: App\Controller\User\UserController::index
  methods: GET

showInstructor:
  path: /instructor/{id}
  controller: App\Controller\User\UserController::showInstructor
  methods: GET

courses:
  path: /courses/user/{id}
  controller: App\Controller\User\UserController::getUserCourses
  methods: GET

instructor_content:
  path: /content/user/{id}
  controller: App\Controller\User\UserController::getUserContent
  methods: GET  

infos:
  path: /user/infos/{id}
  controller: App\Controller\User\UserController::getUserInfos
  methods: GET

instructors:
  path: /users/instructors
  controller: App\Controller\User\UserController::getInstructors
  methods: GET

update:
  path: /user/{id}
  controller: App\Controller\User\UserController::edit
  methods: [PUT, POST]

update_password:
  path: /user/{id}/password
  controller: App\Controller\User\UserController::updatePassword
  methods: PUT

delete_user:
  path: /user/{id}
  controller: App\Controller\User\UserController::deleteAccount
  methods: DELETE

add_interests:
  path: /user/interests
  controller: App\Controller\User\UserController::addInterests
  methods: POST

enrollements:
  path: enroll/{courseId}
  controller: App\Controller\User\UserController::enroll
  methods: POST

reviews:
  path: /{courseId}/reviews
  controller: App\Controller\User\UserController::getCourseReviews
  methods: GET

add_review:
  path: /courses/{courseId}/reviews
  controller: App\Controller\User\UserController::createReviewForCourse
  methods: POST

user_follow:
  path: /follow
  controller: App\Controller\User\UserController::follow
  methods: POST

user_unfollow:
  path: /unfollow
  controller: App\Controller\User\UserController::unfollow
  methods: POST

suggested_people:
  path: /suggested/{userId}
  controller: App\Controller\User\UserController::suggested
  methods: GET

followers:
  path: /followers/{userId}
  controller: App\Controller\User\UserController::followers
  methods: GET

followings:
  path: /followings/{userId}
  controller: App\Controller\User\UserController::followings
  methods: GET

user_posts:
  path: /user/posts/{id}
  controller: App\Controller\User\UserController::getUserPosts
  methods: GET

student_enrollement_courses:
  path: /student/{id}/courses/
  controller: App\Controller\User\UserController::getStudentCourseTitles
  methods: GET

user_current_plan:
  path: /plans/user/{userId}
  controller: App\Controller\User\UserController::getUserCurrentPlan
  methods: GET
