index:
  path: users
  controller: App\Controller\User\UserController::index
  methods: GET

showInstructor:
  path: /instructor/{id}
  controller: App\Controller\User\UserController::showInstructor
  methods: GET  

courses:
  path: /courses/user/{id}
  controller: App\Controller\User\UserController::getUserCourses
  methods: GET

infos:
  path: /user/infos/{id}
  controller: App\Controller\User\UserController::getUserInfos
  methods: GET

instructors:
  path: /users/instructors
  controller: App\Controller\User\UserController::getInstructors
  methods: GET

update:
  path: /user/{id}
  controller: App\Controller\User\UserController::edit
  methods: [PUT, POST]

update_password:
  path: /user/{id}/password
  controller: App\Controller\User\UserController::updatePassword
  methods: PUT

delete_user:
  path: /user/{id}
  controller: App\Controller\User\UserController::deleteAccount
  methods: DELETE

add_interests:
  path: /user/interests
  controller: App\Controller\User\UserController::addInterests
  methods: POST
