name: Security Audit
on: [push, pull_request]
jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ms-learning-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
        working-directory: ./ms-learning-backend

      - name: Caching deps
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashFiles('ms-learning-backend/composer.json') }}
          restore-keys: |
            php8.2-composer-latest-

      - name: Update composer
        run: composer self-update
        working-directory: ./ms-learning-backend

      - name: Create .env file (if needed)
        run: echo "APP_ENV=ci" > .env
        working-directory: ./ms-learning-backend

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        working-directory: ./ms-learning-backend

      - name: Security audit
        run: |
          composer audit \
            --no-dev \
            --abandoned="report" \
            --ignore-severity="low" \
            --format="json" \
            --no-ansi \
            > /tmp/security-audit.json
        working-directory: ./ms-learning-backend

      - name: Upload security audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit
          path: /tmp/security-audit.json
