name: Symfony CI/CD

on: [push, pull_request]

jobs:
  test:
    name: Run Symfony Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Core Services
        run: |
          docker-compose up -d db elasticsearch
          docker ps

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mslearning_db mysqladmin ping -h localhost --silent; do
            echo "MySQL not ready yet - sleeping"
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Wait for Elasticsearch
        run: |
          echo "Waiting for Elasticsearch..."
          until curl -s http://localhost:9200/_cluster/health | grep -q '"status":"green"'; do
            echo "Elasticsearch not ready yet - sleeping"
            sleep 5
          done
          echo "Elasticsearch is ready!"

      - name: Prepare Environment
        run: |
          cd ms-learning-backend
          cp .env.test .env
          echo "DATABASE_URL=mysql://root:@mslearning_db:3306/ms-learning?serverVersion=8&charset=utf8mb4" >> .env
          echo "ELASTICSEARCH_DSN=http://mslearning_elasticsearch:9200" >> .env
          echo "MERCURE_ENABLED=false" >> .env
          cd ..

      - name: Start Application Services
        run: docker-compose up -d php

      - name: Install Dependencies (without scripts)
        run: |
          docker exec mslearning-php bash -c "cd /var/www/html && composer install --prefer-dist --no-interaction --no-progress --no-scripts"

      - name: Run Manual Setup
        run: |
          docker exec mslearning-php bash -c "cd /var/www/html && composer dump-autoload --optimize"
          docker exec mslearning-php bash -c "cd /var/www/html && php bin/console cache:clear"
          docker exec mslearning-php bash -c "cd /var/www/html && php bin/console assets:install"
          docker exec mslearning-php bash -c "cd /var/www/html && php bin/console doctrine:database:create --if-not-exists"
          docker exec mslearning-php bash -c "cd /var/www/html && php bin/console doctrine:schema:update --force"
          docker exec mslearning-php bash -c "cd /var/www/html && php bin/console elasticsearch:index:create"

      - name: Run Tests
        run: docker exec mslearning-php bash -c "cd /var/www/html && php bin/phpunit"

      - name: Stop containers
        if: always()
        run: docker-compose down
