name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Symfony Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: ms-learning
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php8.2-composer-latest-

      - name: Install Dependencies
        working-directory: ms-learning-backend
        run: composer install --prefer-dist --no-scripts --no-interaction --no-progress --optimize-autoloader

      - name: Clear Symfony Cache
        working-directory: ms-learning-backend
        run: php bin/console cache:clear --env=test
      
      - name: Create .env.test File in CI
        working-directory: ms-learning-backend
        run: |
          echo "APP_ENV=test" > .env.test
          echo "DATABASE_URL=mysql://root:@127.0.0.1:3306/ms-learning" >> .env.test
      
      - name: Prepare the Database
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:create --env=test
          php bin/console cache:clear --env=test
        working-directory: ms-learning-backend

      - name: Run Tests
        working-directory: ms-learning-backend
        run: composer app:tests
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:@127.0.0.1:3306/ms-learning
