name: Symfony CI/CD

on: [push, pull_request]

jobs:
  test:
    name: Run Symfony Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Docker Containers (without dependencies)
        run: |
          docker-compose up -d db  # Start only DB first
          docker ps

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mslearning_db mysqladmin ping -h localhost --silent; do
            echo "MySQL not ready yet - sleeping"
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Copy .env file
        run: |
          cp .env.test .env
          echo "DATABASE_URL=mysql://root:@mslearning_db:3306/ms-learning?serverVersion=8&charset=utf8mb4" >> .env

      - name: Start remaining services
        run: docker-compose up -d

      - name: Install Dependencies
        run: |
          docker exec mslearning-php composer install --prefer-dist --no-interaction --no-progress --no-scripts
          docker exec mslearning-php composer dump-autoload --optimize

      - name: Run post-install scripts manually
        run: |
          docker exec mslearning-php php bin/console cache:clear
          docker exec mslearning-php php bin/console assets:install

      - name: Create Database Schema
        run: |
          docker exec mslearning-php php bin/console doctrine:database:create --if-not-exists
          docker exec mslearning-php php bin/console doctrine:schema:update --force

      - name: Run Symfony Tests
        run: docker exec mslearning-php php bin/phpunit

      - name: Stop containers
        if: always()
        run: docker-compose down
