name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    services:
      database:
        image: mariadb:10.7.3
        env:
          MARIADB_USER: root
          MARIADB_ROOT_PASSWORD: 
          MARIADB_DATABASE: ms-learning
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching deps
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Update composer
        run: composer self-update

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Create .env.test File in CI
        working-directory: ms-learning-backend
        run: |
          echo "APP_ENV=test" > .env.test
          echo "DATABASE_URL=mysql://root:@127.0.0.1:${{ job.services.database.ports['3306'] }}/ms-learning" >> .env.test

      - name: Ensure .env.test is Used in CI
        working-directory: ms-learning-backend
        run: cp .env.test .env

      - name: Prepare the Database
        working-directory: ms-learning-backend
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:create --env=test
          php bin/console cache:clear --env=test

      - name: Run Tests
        working-directory: ms-learning-backend
        run: composer app:tests
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:@127.0.0.1:${{ job.services.database.ports['3306'] }}/ms-learning